enhance create job ui
kalibani/Genio pull request #49
Opened 2024-05-14 13:55 UTC by maulanamaleek

Ticket: https://app.clickup.com/t/86epbf88f
| Status | ✅ Ready to Merge |
| -- | -- |

Scope: 
- move title
- fix label placeholder
- add exp years up to 20
- add work model into radio group (as wireframe)
- non gradient progress bar

| Results |
| -- |
|<img width="1800" alt="image" src="https://github.com/kalibani/Genio/assets/67380302/917c0b2d-0c9e-4214-bf09-a84d65104c08">|

2024-05-14 13:56 UTC, maulanamaleek commented
@dwicaksono / @RikoOrlando please help to review 🙏

2024-05-14 14:06 UTC, dwicaksono requested changes

2024-05-14 14:06 UTC, dwicaksono commented on components/job/create-job/form-create.tsx
> -                    <Select
mas @maulanamaleek  sorry miscom kayaknya disni tetap select dropdown mas field work model cuman yang nambah itu isiannya aja sama kayak yang experience. 🚀

2024-05-15 00:42 UTC, maulanamaleek commented on components/job/create-job/form-create.tsx
> -                    <Select
oh oke mas tetap dropdown ya

2024-05-15 02:00 UTC, dwicaksono approved these changes

2024-05-15 02:00 UTC, merged